cluster:
  enabled: true
  slaveCount: 1 # Reduce replicas to 1

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

persistence:
  enabled: true  # Set to true if you want to use persistent volumes

service:
  type: ClusterIP
  port: 6379
