name: CI/CD for Infrastructure and Redis Deployment

on:
  push:
    branches:
      - main

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2  # Define the AWS region here

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Create or verify the S3 bucket and DynamoDB table for backend
    - name: Create Backend Resources
      run: |
        # Create S3 Bucket if it doesn't exist
        if ! aws s3api head-bucket --bucket your-terraform-state-bucket --region ${{ env.AWS_REGION }} 2>/dev/null; then
          aws s3api create-bucket --bucket your-terraform-state-bucket --region ${{ env.AWS_REGION }} --create-bucket-configuration LocationConstraint=${{ env.AWS_REGION }}
        fi

        # Enable versioning on the bucket
        aws s3api put-bucket-versioning --bucket your-terraform-state-bucket --region ${{ env.AWS_REGION }} --versioning-configuration Status=Enabled

        # Create DynamoDB Table if it doesn't exist
        if ! aws dynamodb describe-table --table-name terraform-lock-table --region ${{ env.AWS_REGION }} 2>/dev/null; then
          aws dynamodb create-table \
            --table-name terraform-lock-table \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --region ${{ env.AWS_REGION }}
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: setup-backend
    env:
      AWS_REGION: us-west-2  # Define the AWS region here

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up AWS credentials for Terraform and EKS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Adjust as needed

    # Set up Terraform with the official Terraform GitHub Action (using version 1.9.5)
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    # Initialize Terraform
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    # Plan Terraform changes
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan

    # Apply Terraform changes to provision infrastructure
    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

    # Install kubectl
    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.30.3' # Match your EKS version

    # Set up kubectl config from GitHub Secrets
    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # Install Helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # Deploy Redis using Helm (without overriding replica settings)
    - name: Deploy Redis Cluster
      run: |
        helm upgrade --install redis ./helm/redis -f ./helm/redis/values.yaml

    # Ensure Redis is deployed successfully
    - name: Check Redis Deployment
      run: kubectl rollout status statefulset redis-master

    # Optional: Monitor Redis deployment
    - name: Verify Redis Pods
      run: kubectl get pods -l app.kubernetes.io/name=redis
